DECLARE
  MINIMO NUMBER;
BEGIN
  SELECT MIN(TAMANO)  INTO MINIMO FROM EJEMPLARESMARIPOSAS;
  dbms_output.put_line(MINIMO);
 	IF  MINIMO < 50 THEN
	 DBMS_OUTPUT.PUT_LINE('NO, ES MENOR DE 50');
	ELSE
	  DBMS_OUTPUT.PUT_LINE('ES MAYOR A 50');
	END IF;
END;
-- tamaño minimo de la mariposa y sacarlo por consola

-- 1

CREATE OR REPLACE 
PROCEDURE ESCRIBE
AS 
BEGIN 
	dbms_output.put_line ('Hola mundo');
END;
----
BEGIN 
	ESCRIBE;
END;

-- 2
CREATE OR REPLACE 
PROCEDURE ESCRIBE_MENSAJE(MENSAJE varchar2)
AS
BEGIN 
	 DBMS_OUTPUT.PUT_LINE (MENSAJE);
END;
----
BEGIN 
	ESCRIBE_MENSAJE('MENSAJE');
END;

-- 3
CREATE OR REPLACE PROCEDURE SERIE (MINIMO NUMBER, MAXIMO NUMBER, PASO NUMBER)
IS
  CONTADOR NUMBER := MINIMO;
BEGIN
  WHILE CONTADOR <= MAXIMO LOOP
    DBMS_OUTPUT.PUT_LINE(CONTADOR);
    CONTADOR := CONTADOR + PASO;
  END LOOP;
END;

----
BEGIN
  SERIE(1, 10, 2);
END;

-- 4
CREATE OR REPLACE FUNCTION AZAR(MINIMO NUMBER, MAXIMO NUMBER) RETURN NUMBER
IS
  NUM_AZAR NUMBER;
BEGIN
  NUM_AZAR := ROUND(DBMS_RANDOM.VALUE(MINIMO, MAXIMO));
  RETURN NUM_AZAR;
END;
----
DECLARE
  NUM_AZAR NUMBER;
BEGIN
  NUM_AZAR := AZAR(1, 10);
  DBMS_OUTPUT.PUT_LINE('Número al azar: ' || NUM_AZAR);
END;

-- 5
CREATE OR REPLACE FUNCTION NOTA (NOTA NUMBER)
RETURN varchar2
IS
BEGIN 
	IF (NOTA>10 OR NOTA<0) THEN
		RETURN ('Valores no válidos');
	ELSIF (NOTA < 5) THEN
		RETURN ('Insuficiente');
	ELSIF (NOTA = 5) THEN
		RETURN ('Suficiente');
	ELSIF (NOTA > 5 AND NOTA <=7) THEN
		RETURN ('Bien');
	ELSIF (NOTA > 7 AND NOTA <=8) THEN
		RETURN ('Notable');
	ELSIF (NOTA > 8 AND NOTA <=10) THEN
		RETURN ('Sobresaliente');
	END IF;
END;
----
SELECT NOTA(10) FROM DUAL;
SELECT NOTA(6) FROM DUAL;

